version: "3.8" # Specify the version of the Docker Compose file
services:
  wiremock:
    image: wiremock/wiremock:2.35.0
    ports:
      - "8091:8080"
    volumes:
      - ./local/wiremock/mappings/:/home/wiremock/mappings
      - ./local/wiremock/__files/:/home/wiremock/__files
    environment:
      WIREMOCK_OPTIONS: "--local-response-templating, --root-dir=/home/wiremock"