default:
  image: maven:3.8.1-openjdk-11

stages:
  - start
  - test

start-springboot:
  stage: start
  script:
    - echo "Starting the Spring Boot application"
    - mvn spring-boot:run &
    - echo "Waiting for the Spring Boot application to start"
    - sleep 30 # Adjust the sleep time if needed
    - echo "Spring Boot application started successfully"

test-job:
  stage: test
  script:
    - echo "Listing directory contents for debugging"
    - ls -la # Debugging step to check the directory structure
    - echo "Navigating to the Maven project root directory"
    - cd brunao || exit 1 # Replace 'brunao' with the correct directory containing the pom.xml
    - echo "Installing the project dependencies"
    - mvn clean install -DskipTests
    - echo "Running the tests"
    - mvn test -Denv=homolog
  artifacts:
    paths:
      - "brunao/target/report.html"
      - "brunao/target/report.json"
  dependencies:
    - start-springboot
  when: on_success