jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
      - run: cd BackEndFilmes/brunao && mvn clean install -DskipTests
      - run: |
          cd BackEndFilmes/brunao
          nohup mvn spring-boot:run > app.log 2>&1 &
          for i in {1..60}; do
            if curl --fail http://localhost:8081/actuator/health; then
              echo "Spring Boot application is up and running"
              break
            fi
            sleep 2
          done
      - run: cd BackEndFilmes/brunao && mvn test -Denv=homolog