name: Spring Boot CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Start Wiremock
        run: |
          docker run -d \
            --name wiremock \
            -p 8091:8080 \
            -v ${{ github.workspace }}/BackEndFilmes/brunao/local/wiremock/mappings:/home/wiremock/mappings \
            -v ${{ github.workspace }}/BackEndFilmes/brunao/local/wiremock/__files:/home/wiremock/__files \
            -e WIREMOCK_OPTIONS="--local-response-templating, --root-dir=/home/wiremock" \
            --user $(id -u):$(id -g) \
            wiremock/wiremock:2.35.0

      - name: Build Spring Boot application
        run: |
          cd BackEndFilmes/brunao
          mvn clean install -DskipTests

      - name: Start Spring Boot application
        run: |
          cd BackEndFilmes/brunao
          nohup mvn spring-boot:run > app.log 2>&1 &
          for i in {1..30}; do
            if curl -s http://localhost:8081/actuator/health | grep UP; then
              echo "Spring Boot is up!"
              break
            fi
            echo "Waiting for Spring Boot..."
            sleep 5
          done

      - name: Run tests
        run: |
          cd BackEndFilmes/brunao
          mvn test

      - name: Upload test reports
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            BackEndFilmes/brunao/target/surefire-reports/
            BackEndFilmes/brunao/target/cucumber/report.html
            BackEndFilmes/brunao/target/cucumber/report.json