name: Spring Boot CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  start-springboot:
    name: Start Spring Boot Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Start Spring Boot application
        run: |
          echo "Starting the Spring Boot application"
          cd BackEndFilmes/brunao
          mvn spring-boot:run &
          echo "Waiting for the Spring Boot application to start"
          sleep 30
          echo "Spring Boot application started successfully"

  test-job:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: start-springboot
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: List directory contents for debugging
        run: ls -la

      - name: Navigate to Maven project root directory
        run: cd BackEndFilmesInGitActions/BackEndFilmes/brunao || exit 1

      - name: Install project dependencies
        run: mvn clean install -DskipTests

      - name: Run tests
        run: mvn test -Denv=homolog

      - name: Upload test artifacts
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: |
            BackEndFilmes/brunao/target/report.html
            BackEndFilmes/brunao/target/report.json
