name: Spring Boot CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  start-services:
    name: Start Services
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Start Wiremock (docker run)
        run: |
          docker run -d \
            -p 8091:8080 \
            -v ${{ github.workspace }}/local/wiremock/mappings:/home/wiremock/mappings \
            -v ${{ github.workspace }}/local/wiremock/__files:/home/wiremock/__files \
            -e WIREMOCK_OPTIONS="--local-response-templating, --root-dir=/home/wiremock" \
            --name wiremock wiremock/wiremock:2.35.0

      - name: Start Spring Boot application
        run: |
          echo "Starting the Spring Boot application"
          cd BackEndFilmes/brunao
          mvn spring-boot:start &
          echo "Waiting for the Spring Boot application to start"
          for i in {1..60}; do  # Increased retries
            if curl --fail http://127.0.0.1:8081/actuator/health; then
              echo "Spring Boot application is up and running"
              break
            fi
            echo "Waiting for Spring Boot application..."
            sleep 10  # Increased wait time
          done

  test-job:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: start-services
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: List directory contents for debugging
        run: |
          echo "Listing directory contents for debugging"
          ls -la

      - name: Install project dependencies
        run: |
          echo "Installing project dependencies"
          cd BackEndFilmes/brunao
          mvn clean install -DskipTests

      - name: Run tests
        run: |
          echo "Running tests"
          cd BackEndFilmes/brunao
          mvn test -Denv=homolog

#      - name: Upload test artifacts
#        uses: actions/upload-artifact@v3
#        with:
#          name: test-reports
#          path: |
#            BackEndFilmes/brunao/target/report.html
#            BackEndFilmes/brunao/target/report.json