name: Spring Boot CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  start-springboot:
    name: Start Spring Boot Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Install Docker Compose
        run: |
          echo "Installing Docker Compose"
          sudo apt-get update
          sudo apt-get install docker-compose -y

      - name: Build with Maven
        run: mvn clean install

      - name: Set up Docker Compose
        run: |
          echo "Setting up Docker Compose"
          docker-compose -f ./docker-compose.yml up -d
          echo "Waiting for WireMock to start"
          sleep 10

      - name: Start Spring Boot application
        run: |
          echo "Starting the Spring Boot application"
          cd BackEndFilmes/brunao
          mvn spring-boot:run &
          echo "Waiting for the Spring Boot application to start"
          sleep 30
          echo "Spring Boot application started successfully"

  test-job:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: start-springboot
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: List directory contents for debugging
        run: |
          echo "Listing directory contents for debugging"
          ls -la

      - name: Navigate to Maven project root directory
        run: |
          echo "Navigating to Maven project root directory"
          cd BackEndFilmes/brunao

      - name: Install project dependencies
        run: |
          echo "Installing project dependencies"
          cd BackEndFilmes/brunao
          mvn clean install -DskipTests

      - name: Run tests
        run: |
          echo "Running tests"
          cd BackEndFilmes/brunao
          mvn test -Denv=homolog

      - name: Upload test artifacts
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: |
            BackEndFilmes/brunao/target/report.html
            BackEndFilmes/brunao/target/report.json